json.array!(@stage_infos) do |stage_info|
  json.extract! stage_info, :id, :STAGE_ID, :AREA_ID, :STAGE_NUMBER, :OPEN, :TYPE, :LEVEL, :COORDINATE, :BGM, :BG_COLOR, :NAME, :EXPLAIN, :CHARACTER_LEVEL, :STAMINA, :PHASE, :MONSTER, :ITEM, :STAGE_ICON, :CLEAR_SCORE, :CLEAR_EXP, :CLEAR_MONEY, :CLEAR_1_REWARD, :CLEAR_1_REWARD_PROBABILITY, :CLEAR_2_REWARD, :CLEAR_2_REWARD_PROBABILITY, :CLEAR_3_REWARD, :CLEAR_3_REWARD_PROBABILITY, :START_SCENARIO, :END_SCENARIO, :BG_PREFEB, :INFI_TOWER_SP_REWARD, :INFI_TOWER_PREVIEW
  json.url stage_info_url(stage_info, format: :json)
end
